version: '2'
services:
  web:
    restart: always
    build: .
    ports:
     - "8000:80"
    expose:
     - "80"
    volumes:
     - .:/app
    networks:
     - escuela
     - default
networks:
  default:
  escuela:
    external: true