version: '2'
services:
  web:
    restart: always
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
     - "8080:8080"
    networks:
      - escuela
      - default
    expose:
     - "8080"
    volumes:
     - /root/escuela/:/app
networks:
  default:
  escuela:
    external: true
